#!/usr/bin/env bash
# Bootstrap the {{repo}}-prod 1Password tier and place its read-only SA token
# on the rotation box. Idempotent — safe to re-run except for SA minting
# (a fresh token requires deleting the existing SA first, since 1P shows the
# token only once).
#
# Runs from a workstation with:
#   - a personal my.1password.com admin session (biometric / desktop-app auth)
#   - SSH access to the rotation box (set ROTATION_HOST)
#   - a 1Password vault to archive the SA token in (set ARCHIVE_VAULT — it must
#     already exist; §1 checks, because §5 writes the token there and 1P shows
#     that token only once)
#   - existing ~/.config/op/dev-token (used by the final isolation check)
#
# Generated by /sdlc:secrets --scaffold-prod. Before first run: substitute
# {{repo}}, {{rotation_host}}, and {{archive_vault}} (or set the matching env
# vars), then fill the ITEM SEED section with your repo's real secret sources.
# See docs/SECRETS.md for the tier model.
set -euo pipefail

# ─── Config (edit per repo) ────────────────────────────────────────
ACCOUNT="my.1password.com"
REPO="{{repo}}"                                       # this repo's short name
SEED_CONFIGURED=0                                     # flip to 1 after filling ITEM SEED (§3)
VAULT="${REPO}-prod"
SA_NAME="${VAULT}-ro"
# The default is quoted: bash closes ${...} at the first unquoted '}', so an
# unquoted {{placeholder}} default leaks a literal '}}' onto any env override.
ROTATION_HOST="${ROTATION_HOST:-"{{rotation_host}}"}" # deploy box that holds the prod token; or set via env
PROD_TOKEN_PATH="\$HOME/.config/op/${VAULT}-token"    # on rotation host
ARCHIVE_VAULT="${ARCHIVE_VAULT:-"{{archive_vault}}"}" # vault where the SA token is archived; or set via env
SA_TOKEN_ITEM="${VAULT}-service-account-token"        # item title in $ARCHIVE_VAULT

# ─── Sentinels — fail loud on unfilled template ────────────────────
for _v in REPO ROTATION_HOST ARCHIVE_VAULT; do
  # Trim surrounding whitespace before testing: ${VAR:-default} treats a blank
  # string as "set", so "   " would otherwise sail through as a real value.
  _val="${!_v}"
  _val="${_val#"${_val%%[![:space:]]*}"}"
  _val="${_val%"${_val##*[![:space:]]}"}"
  case "$_val" in
    *"{{"*|*"}}"*|"")
      printf '✗ %s is still a template placeholder or empty (%s). Replace it before running.\n' "$_v" "${!_v}" >&2
      exit 1
      ;;
  esac
done
unset _v _val

# ─── Helpers ───────────────────────────────────────────────────────
say() { printf '\033[1;36m==\033[0m %s\n' "$*"; }
ok()  { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m!\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ─── 0. Preflight ──────────────────────────────────────────────────
say "Preflight"
command -v op >/dev/null || die "1password CLI (op) not installed"
[ -t 0 ] || die "requires interactive TTY — 'op signin' opens a biometric/password prompt"
[ -f "$HOME/.config/op/dev-token" ] \
  || die "expected dev-token at ~/.config/op/dev-token — set up the dev tier first (run /sdlc:secrets)"
ssh -o BatchMode=yes -o ConnectTimeout=5 "$ROTATION_HOST" true 2>/dev/null \
  || die "cannot reach $ROTATION_HOST via SSH"
ok "op $(op --version), $ROTATION_HOST reachable, dev-token present"

# ─── 1. Personal admin op session ──────────────────────────────────
say "Personal admin op session ($ACCOUNT)"
if ! op --account "$ACCOUNT" whoami >/dev/null 2>&1; then
  eval "$(op signin --account "$ACCOUNT")"
fi
op --account "$ACCOUNT" whoami | sed 's/^/  /'
OP="op --account $ACCOUNT"

# The archive vault must exist BEFORE the SA is minted in §4. 1Password shows a
# service-account token exactly once; if the archive write in §5 is the first
# thing to touch this vault and the name is wrong, `set -e` kills the script
# holding the only copy of a live prod token, and recovery means deleting the SA
# in the admin UI and starting over. Fail here instead, where nothing is lost.
# Catches the common failure (a typo'd or nonexistent vault). It does NOT prove
# write access — a vault you can see but not write to still fails in §5. If that
# happens, the SA exists and its token is gone: delete the SA in the 1P admin UI
# and re-run.
$OP vault get "$ARCHIVE_VAULT" >/dev/null 2>&1 \
  || die "archive vault '$ARCHIVE_VAULT' not found — create it (or fix ARCHIVE_VAULT) before minting"
ok "archive vault $ARCHIVE_VAULT reachable"

# ─── 2. Vault (idempotent) ─────────────────────────────────────────
say "Vault $VAULT"
if $OP vault get "$VAULT" >/dev/null 2>&1; then
  ok "$VAULT already exists"
else
  $OP vault create "$VAULT" --description "${REPO} prod-tier secrets (see docs/SECRETS.md)" >/dev/null
  ok "created $VAULT"
fi

# ─── 3. ITEM SEED (customize per repo) ─────────────────────────────
# On subsequent runs the whole seed block skips if all target items exist,
# so SA-rotation re-runs never touch the source.
#
# TODO: list the item titles you'll create below (kebab-case logical groups):
EXPECTED_ITEMS=(
  # google-oauth
  # auth
  # gemini
  # cloudflare
)

say "Seed items"
missing=()
for title in "${EXPECTED_ITEMS[@]}"; do
  $OP item get "$title" --vault "$VAULT" >/dev/null 2>&1 || missing+=("$title")
done

if [ ${#missing[@]} -eq 0 ] && [ ${#EXPECTED_ITEMS[@]} -gt 0 ]; then
  ok "all items already exist — skipping seed"
else
  if [ ${#EXPECTED_ITEMS[@]} -eq 0 ]; then
    warn "no EXPECTED_ITEMS declared — fill in the ITEM SEED block first"
  else
    warn "missing items: ${missing[*]} — seeding"
  fi

  # TODO: read source values into vars. Common patterns:
  #
  #   # From an existing 1P vault (e.g. a pre-migration stash):
  #   FIELD_A=$($OP read "op://<legacy-vault>/${REPO}_group/field")
  #
  #   # From Stripe Projects:
  #   eval "$(stripe projects env --pull --format=export)"
  #
  #   # From a running process's env (last resort):
  #   FIELD_A="$(ssh $ROTATION_HOST 'grep ^FOO= ~/deploy/${REPO}/.env | cut -d= -f2-')"
  #
  # Then upsert items — each with all its fields on one op call:
  upsert() {
    local title=$1; shift
    if $OP item get "$title" --vault "$VAULT" >/dev/null 2>&1; then
      $OP item edit "$title" --vault "$VAULT" "$@" </dev/null >/dev/null
      ok "updated $title"
    else
      $OP item create --vault "$VAULT" --category "API Credential" --title "$title" "$@" </dev/null >/dev/null
      ok "created $title"
    fi
  }

  # TODO: fill in the upserts for each item:
  #
  #   upsert google-oauth \
  #     "client-id[text]=$GOOG_CLIENT_ID" \
  #     "client-secret[password]=$GOOG_CLIENT_SECRET" \
  #     "redirect-uri[text]=$GOOG_REDIRECT_URI"
  #
  #   upsert auth \
  #     "better-auth-secret[password]=$BETTER_AUTH_SECRET" \
  #     "token-encryption-key[password]=$TOKEN_ENC_KEY"
  [ "$SEED_CONFIGURED" = "1" ] \
    || die "SEED_CONFIGURED=0 — fill EXPECTED_ITEMS + source reads + upsert calls, then set SEED_CONFIGURED=1 at the top."
fi

# ─── 4. Mint read-only SA scoped to the prod vault ────────────────
say "Service account $SA_NAME"
# The 1P CLI has no `service-account list` subcommand — try-create and parse
# the error to detect an existing SA. CLI hard cap: --expires-in maxes at
# 90 days (2160h); longer is rejected.
SKIP_MINT=0
SA_OUTPUT=$($OP service-account create "$SA_NAME" \
  --vault "$VAULT":read_items \
  --expires-in 90d \
  --raw 2>&1) || {
    if echo "$SA_OUTPUT" | grep -qiE 'already (exists|in use)|name.*taken'; then
      warn "$SA_NAME already exists. 1P only shows the token at creation;"
      warn "rotation requires deleting the existing SA in the 1P admin UI"
      warn "(Developer → Service Accounts), then re-running this script."
      warn "Skipping mint + token push. Vault + items were still applied."
      SKIP_MINT=1
    else
      printf '%s\n' "$SA_OUTPUT" >&2
      die "unexpected service-account create error"
    fi
  }

if [ "$SKIP_MINT" != "1" ]; then
  SA_TOKEN="$SA_OUTPUT"
  [[ "$SA_TOKEN" == ops_* ]] || { printf '%s\n' "$SA_OUTPUT" >&2; die "SA token missing ops_ prefix"; }
  ok "minted $SA_NAME (expires 90d — rotate before then)"

  # ─── 5. Archive token in the archive vault ──────────────────────
  say "Archive token in $ARCHIVE_VAULT vault"
  if $OP item get "$SA_TOKEN_ITEM" --vault "$ARCHIVE_VAULT" >/dev/null 2>&1; then
    $OP item edit "$SA_TOKEN_ITEM" --vault "$ARCHIVE_VAULT" \
      "credential[password]=$SA_TOKEN" </dev/null >/dev/null
    ok "updated $ARCHIVE_VAULT/$SA_TOKEN_ITEM"
  else
    $OP item create --vault "$ARCHIVE_VAULT" --category "API Credential" \
      --title "$SA_TOKEN_ITEM" "credential[password]=$SA_TOKEN" </dev/null >/dev/null
    ok "created $ARCHIVE_VAULT/$SA_TOKEN_ITEM"
  fi

  # ─── 6. Push token to rotation host ─────────────────────────────
  # mkdir + write in one session so a failed write doesn't leave an orphan
  # ~/.config/op directory behind.
  say "Push token to $ROTATION_HOST:$PROD_TOKEN_PATH"
  # shellcheck disable=SC2029  # PROD_TOKEN_PATH is literal "$HOME/..." on purpose — expands on remote
  printf '%s' "$SA_TOKEN" | ssh "$ROTATION_HOST" \
    "mkdir -p ~/.config/op && chmod 700 ~/.config/op && umask 077 && cat > $PROD_TOKEN_PATH && chmod 600 $PROD_TOKEN_PATH"
  ok "placed on $ROTATION_HOST"
  unset SA_TOKEN SA_OUTPUT
fi

# ─── 7. Verify isolation ───────────────────────────────────────────
say "Verify isolation"

# 7a. dev-token cannot reach the prod vault
FIRST_ITEM="${EXPECTED_ITEMS[0]:-}"
if [ -z "$FIRST_ITEM" ]; then
  die "no items declared — cannot verify isolation. Fill EXPECTED_ITEMS and rerun; a script that reports 'Done' without proving isolation is worse than useless."
fi
{
  # Item-scoped probes: `op item get` succeeds when the SA can see the vault
  # AND the item, and fails otherwise. Success on the dev-token side would
  # mean isolation broke, so we invert the branch.
  if OP_SERVICE_ACCOUNT_TOKEN="$(cat "$HOME/.config/op/dev-token")" \
       op item get "$FIRST_ITEM" --vault "$VAULT" >/dev/null 2>&1; then
    die "ISOLATION BROKEN: dev-token can access op://$VAULT/$FIRST_ITEM"
  fi
  ok "dev-token blocked from op://$VAULT/* — isolation intact"

  # 7b. rotation host's prod-token CAN read prod
  # shellcheck disable=SC2029  # PROD_TOKEN_PATH is literal "$HOME/..." on purpose — expands on remote
  if ssh "$ROTATION_HOST" \
    "OP_SERVICE_ACCOUNT_TOKEN=\"\$(cat $PROD_TOKEN_PATH)\" op item get \"$FIRST_ITEM\" --vault \"$VAULT\" >/dev/null 2>&1"; then
    ok "prod-token on $ROTATION_HOST reads op://$VAULT/* — plumbing works"
  else
    die "prod-token on $ROTATION_HOST cannot read op://$VAULT/*. Check $PROD_TOKEN_PATH"
  fi
}

say "Done"
cat <<EOF

Next (manual):
  1. Rotate prod secrets to the new source per docs/DEPLOY.md.
     Use the prod-token on $ROTATION_HOST:
       export OP_SERVICE_ACCOUNT_TOKEN="\$(cat $PROD_TOKEN_PATH)"
       # …then your deploy tool's 'set secret' commands, reading from
       # op://$VAULT/<group>/<field>
  2. Schedule the 90-day rotation reminder (scheduler or calendar).
  3. Retire the legacy secret source once prod is verified healthy.
EOF
